version: '3'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:latest
    #image: homeassistant/raspberrypi3-homeassistant:stable
    #image: homeassistant/raspberrypi4-homeassistant:stable
    command: [ "python", "-m", "homeassistant", "--config", "/config", "--log-rotate-days", '3' ] # Need to rotate home-assistant.log
    privileged: true
    volumes:
    - "${HOMEASSISTANT_CONFIGDIR}:/config"
    environment:
    - "TZ=Europe/Rome"
    network_mode: host
    restart: always
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    ports:
    - "${MOSQUITTO_PORT}:${MOSQUITTO_PORT}"
    volumes:
    - "${PWD}/mosquitto/config:/mosquitto/config"
    environment:
    - "TZ=Europe/Rome"
    restart: always
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
    - "80:80"    # Needed for HTTP-01 challenge
    #- "443:443"    # Needed for TLS-ALPN-01 challenge 
    - "${HOMEASSISTANT_EXTERNAL_PORT}:${HOMEASSISTANT_EXTERNAL_PORT}"
    environment:
    - "HOMEASSISTANT_LOCAL_URL=${HOMEASSISTANT_LOCAL_URL}"
    - "HOMEASSISTANT_EXTERNAL_URL=${HOMEASSISTANT_EXTERNAL_URL}"
    - "TZ=Europe/Rome"
    volumes:
    - "${PWD}/caddy/config/Caddyfile:/etc/caddy/Caddyfile"
    - "${PWD}/caddy/data:/data"
    - "${PWD}/caddy/log:/var/log/caddy"
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:latest
    privileged: true
    volumes:
    - "${PWD}/zigbee2mqtt/config:/app/data"
    - "${PWD}/zigbee2mqtt/log:/var/log/zigbee2mqtt"
    - /run/udev:/run/udev:ro
    devices:
    - "${Z2M_DEVICE_PORT}:${Z2M_DEVICE_PORT}"  # Check correct device address on your system
    restart: on-failure:10
    network_mode: host
    environment:
    - "TZ=Europe/Rome"
  portainer:
    image: portainer/portainer
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
    - ${PORTAINER_PORT}:${PORTAINER_PORT}
    #- 8000:8000    # if you use EDGE Agent uncomment this line
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
      
volumes:
  portainer_data: