version: '3'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:latest
    privileged: true
    command: [ "python", "-m", "homeassistant", "--config", "/config", "--log-rotate-days", '3' ]
    ports:
    - "${HOMEASSISTANT_LOCAL_PORT}:${HOMEASSISTANT_LOCAL_PORT}"
    volumes:
    - "${HOMEASSISTANT_CONFIGDIR}:/config"
    environment:
    - "TZ=Europe/Rome"
    restart: always
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    privileged: true
    ports:
    - "1883:${MOSQUITTO_PORT}"
    volumes:
    - "$PWD/config/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf"
    - "$PWD/data/mosquitto/:/mosquitto/config/data/"
    # Uncommenti following line if you want to use pwfile
    #- "$PWD/config/mosquitto/pwfile:/mosquitto/config/pwfile"
    restart: always
  duckdns:
    image: linuxserver/duckdns
    container_name: duckdns
    environment:
    - "TZ=Europe/Rome"
    - "SUBDOMAINS=${DUCKDNS_SUBDOMAIN}"
    - "TOKEN=${DUCKDNS_TOKEN}"
    restart: unless-stopped
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
    - "80:80"    # Needed for HTTP-01 challenge (https://letsencrypt.org/docs/challenge-types/#http-01-challenge)
    - "${HOMEASSISTANT_EXTERNAL_PORT}:${HOMEASSISTANT_EXTERNAL_PORT}"
    environment:
    - "HOMEASSISTANT_LOCAL_URL=${HOMEASSISTANT_LOCAL_URL}"
    - "HOMEASSISTANT_EXTERNAL_URL=${HOMEASSISTANT_EXTERNAL_URL}"
    volumes:
    - "$PWD/config/Caddyfile:/etc/caddy/Caddyfile"
    - "$PWD/data:/data"
    - "$PWD/config:/config"
#  zigbee2mqtt:
#    container_name: zigbee2mqtt
#    image: koenkk/zigbee2mqtt
#    volumes:
#    - "$PWD/data:/data"
#    #- "$PWD/run/udev:/run/udev:ro"
#    devices:
#    - "/dev/ttyACM0:/dev/ttyACM0"
#    restart: on-failure:100
#    network_mode: host
#    privileged: true
#    environment:
#    - "TZ=Europe/Rome"